#!/bin/bash
sudo cp smiley-mcsmiles-f34-backgrounds.xml /usr/share/gnome-background-properties/
sudo mkdir /usr/share/backgrounds/smiley-mcsmiles-f34-backgrounds
sudo cp *.png /usr/share/backgrounds/smiley-mcsmiles-f34-backgrounds/
cd ../
rm -rf smiley-mcsmiles-f34-backgrounds
